### ISSUE TITLE
which endpoint should i call?

### ISSUE THREAD

**Issue by bassjobsen** [AschPlatform/asch-cli#23]
i try to fix the function to register a Dapp by calling something like that shown below:

`asch-cli -H 127.0.0.1 -P 4096 registerdapp --metafile dapp.json --secret "gesture goose side remember actress frame ceiling buffalo bring slice soap describe"`

The above calls `/peer/transactions` with a `POST` request here: https://github.com/AschPlatform/asch-cli/blob/master/helpers/api.js#L67

The `POST` request calls (as expected) `chain.register()` https://github.com/AschPlatform/asch/blob/master/src/contract/chain.js#L4, but the parameters for  `chain.register()` are NOT set???

As far as i do understand does the `POST` request call  `chain.register()`  via the asch-sandbox. The code of  asch-sandbox isn't readable (WHY NOT?)

Should i use a different end point or goes something wrong in the sandbox? @sqfasd @liangpeili @a1300

**Comment by bassjobsen** [comment]
Notice that i've already tried to use the sandbox code of http://39.107.52.143/dist.tgz

**Comment by liangpeili** [comment]
The registerdapp is replaced by `registerchain`

```
root@asch~$ asch-cli  -P 4096 registerchain -e "stone elephant caught wrong spend traffic success fetch inside blush virtual element" -f dapp.json
```

**Comment by bassjobsen** [comment]
@liangpeili thanks. Did you mean that the command should be replaced? Or is there a new version of `asch-cli` which does has the `registerchain` command already.
The current version on github does not contain the `registerchain` command.

**Comment by liangpeili** [comment]
develop branch. Need to be published .

```
root@asch~$ asch-cli  -P 4096 registerchain -e "stone elephant caught wrong spend traffic success fetch inside blush virtual element" -f dapp.json
0de8d19c5866940af0e09245b8352acd42d14075960335453f758f481f0319d3

```

**Comment by a1300** [comment]
@bassjobsen can this issue be closed?
