### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by hbcrhythm** [AschPlatform/asch-cli#3]
plugins/dapps.js 186 
code:
  dappTrs = AschJS.dapp.createDapp(account.secret, secondSecret, dappParams);
but
  fucntion createDapp first params need to dappParams.

**Comment by sqfasd** [comment]
1.3.4+ has fixed

**Comment by hbcrhythm** [comment]
@sqfasd no fixed. 
asch-cli 1.3.6
![image](https://user-images.githubusercontent.com/6050876/28453557-6b32f2d4-6e2a-11e7-96c8-a11adf815c21.png)

asch-js 1.3.4 
![image](https://user-images.githubusercontent.com/6050876/28453507-43f1969e-6e2a-11e7-902d-b0ea4be3dcfd.png)

i tried to created hello world dapp , there are many mistakes.

**Comment by sqfasd** [comment]
Sorry. The new dapp template generation command and document will be released later
You can deploy a dapp by manual.
Use asch-cli registerdapp to register and then copy the boilerplate project to dapp directory

**Comment by hbcrhythm** [comment]
ok
