### ISSUE TITLE
asch-cli dapps -i does not install the app

### ISSUE THREAD

**Issue by anshuman-singh-93** [AschPlatform/asch-cli#8]
Problem-
once i enter the master key followed by dappId and host-port ,final callback does not execute 

I went through dapps.js inside the plugin folder and seems like you are upgrading to async await feature but did not implement it completely ,i had to make the couple of changes,and then it worked.
is asch-cli project still in development ? if it is when will it be ready for production use.

**Comment by sqfasd** [comment]
https://github.com/AschPlatform/asch/issues/90
